default: &default
  adapter: postgresql
  pool: 5
  database: adm
  host: localhost
  username: postgres
  
development:
  <<: *default


test:
  <<: *default
  database: adm_test

production:
  <<: *default